### PR TITLE
common-tasks: add 'bootloader' section

### PR DESCRIPTION
**Pull request by agordon**
Hi,

After some chatter on IRC, here's a suggestion for 'boot loader' section in the handbook.

regards
-assaf

### CODE REVIEW

**Comment by makruger** [comment]
Hi Gordon, sorry for the delay getting to this. Great work, looks good.

I probably should mention we're using markdown lint to validate things. You can run this locally and we run it using travis-ci as well. 

In this case, it tripped on a couple of lines:

`$ mdl -s markdownlint-rules.rb .`

`./docs/handbook/common-tasks.md:154: MD030 Spaces after list markers`
`./docs/handbook/common-tasks.md:161: MD030 Spaces after list markers`

If you can fix, and commit, I'll merge the changes.

**Comment by xen0l** [comment]
@agordon could you fix mdl warnings?

**Comment by AdrianKoshka** [comment]
@makruger @xen0l If you two are willing to close this PR, I'm going to open one where I've fixed the offending linting issues.

**Comment by makruger** [comment]
@AdrianKoshka, so if I close it, you'll copy the changes and submit your own PR?

**Comment by AdrianKoshka** [comment]
@makruger already did on PR #83

**Comment by makruger** [comment]
@AdrianKoshka, OK closing this PR.

**Pull request closed without merging**
