### PR TITLE
Add info on how to relax a version constraint

### PR DESCRIPTION
**Pull request by timmooney**
None of the getting started documents mention that the userland-incorporation may place version constraints on existing packages, so you might not be able to install your updated version for testing.

One thing about my example that's different from the rest of the documentation (so far) is that my example shows both the command being run and the output, to illustrate the type of error message someone might get when userland-incorporation is blocking a package update.  I don't know if there's a better way to format that example.

### CODE REVIEW

**Comment by alarcher** [comment]
You may need to explain also that openindiana.org should be non-sticky and userland should have a higher priority.

**Comment by timmooney** [comment]
You're right, Aurélien.

On their devel system, as long as they've followed the document and run gmake setup previously, userland was automatically added with a higher priority, but that wouldn't necessarily be true for other systems.

Let me add some additional information and push the additional changes.

**Comment by timmooney** [comment]
I've expanded on the documentation for installing, moving it into an "Install and test" section.  I've also spelled out that it was 'gmake setup' that added the local userland repository and that it made it highest priority.

I moved the documentation about relaxing the version constraint into the the Install and test section, and I've added a note about how to make openindiana.org non-sticky or install the package from userland by using the full package name and version, including the publisher.

Please review.

Thanks,

Tim

**Comment by makruger** [comment]
I'll let Xenol merge this one.

**Comment by xen0l** [comment]
If @alarcher is satisfied, he can merge this one. I was OK even with the previous verison. @alarcher, can you have a look?

**Comment by alarcher** [comment]
@xen0l Approved. I have no credentials to merge PRs on this repo.

**Pull request merged**
