### PR TITLE
Migrate to Github Actions from Travis CI

### PR DESCRIPTION
**Pull request by Toasterson**
With this PR we finaly move the CI to publish the pages from Travis CI to GitHub Actions. This uses a fork of the original mkdocs publishing repo, to add our linting setup from travis and make it closer to our previous setup.

### CODE REVIEW

**Comment by Toasterson** [comment]
The forked action is located at https://github.com/OpenIndiana/mkdocs-deploy-gh-pages
Any change to the forked action.sh in the oi branch work when the action is next executed

**Review by AndWac — APPROVED** [review]

**Comment by JMadgwick** [comment]
This looks good. A few days ago I put together [a different way to do this in my fork](https://github.com/JMadgwick/oi-docs/commit/01958d0cfe24211858eee23d3c1a3af6864cfcd2). My approach installed mkdocs manually (rather than use the mkdocs action) and I included some extra steps for running pandoc and placing the generated PDFs into the site folder before deploying.
I'd not proposed a PR for the commit linked above just yet as there's no page on the wiki to link the PDF versions of the docs to.

I think we should be good to merge this. My only thought is as configured the action is is only triggered by a push to master. This way we won't get any build status indicators on PRs (although if the branch to merge is master in the fork itself we can check that). There's another problem with PRs and GH Actions as it [doesn't automatically build PRs from first time contributors](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks), so a maintainer would need to approve manually in any case.
We of course wouldn't want to run this workflow on PRs as the workflow is committing to the gh-pages branch. We would want to add a new workflow which did just the linting and run that only on PRs. I'm happy to add that later if it would be useful

**Review by JMadgwick — APPROVED** [review]

**Comment by Toasterson** [comment]
> This looks good. A few days ago I put together [a different way to do this in my fork](https://github.com/JMadgwick/oi-docs/commit/01958d0cfe24211858eee23d3c1a3af6864cfcd2). My approach installed mkdocs manually (rather than use the mkdocs action) and I included some extra steps for running pandoc and placing the generated PDFs into the site folder before deploying.
> I'd not proposed a PR for the commit linked above just yet as there's no page on the wiki to link the PDF versions of the docs to.
> 
> I think we should be good to merge this. My only thought is as configured the action is is only triggered by a push to master. This way we won't get any build status indicators on PRs (although if the branch to merge is master in the fork itself we can check that). There's another problem with PRs and GH Actions as it [doesn't automatically build PRs from first time contributors](https://docs.github.com/en/actions/managing-workflow-runs/approving-workflow-runs-from-public-forks), so a maintainer would need to approve manually in any case.
> We of course wouldn't want to run this workflow on PRs as the workflow is committing to the gh-pages branch. We would want to add a new workflow which did just the linting and run that only on PRs. I'm happy to add that later if it would be useful

Yeah yours makes the same but instead of packaging an action it does it in the yaml itself.
I think it would be useful to make an action shell repo like the one I am using for the pdf's and another for the pr check and include those in the correct places.
We could also make one repo with different sub scripts and variables to choose. Whatever people think works best.

We should make the PR workflow lint and build, and also do the PDF building.

In General when working on things, adding an issue or a Draft PR will allow others to see that work and go from there. We should start doing that so we don't duplicate work.

**Comment by JMadgwick** [comment]
I was unsure about using the actions script as it seemed to add complication, at least compared to Travis. I was going to make an issue, I even prepared some of the text for it (partly what I wrote above) :slightly_smiling_face: But I was going to leave it a few days as I've already been committing quite a bit and I don't want it to look like I'm doing my own thing without consulting others.

_I've just noticed a problem with this change._ The markdown inside 'note' boxes is not being parsed anymore [eg in the first box on this page](http://localhost/oi-docs-gh-pages/handbook/getting-started/). I had the same issue when I was setting up mkdocs in GH Actions. The solution is to pin some of the mkdocs dependencies to older versions (as used by Travis). [Details are in this commit](https://github.com/JMadgwick/oi-docs/commit/e5f515f42a2e9c8bf4d67c8996d3200fd6c58738).

You're right about duplication of effort. In future I will be more proactive about preventing that :+1: 
I will raise a new issue for workflows for PR linting/build and potentially another issue for the PDF building, unless combining them into a separate issue is more suitable.

**Comment by Toasterson** [comment]
> _I've just noticed a problem with this change._ The markdown inside 'note' boxes is not being parsed anymore [eg in the first box on this page](http://localhost/oi-docs-gh-pages/handbook/getting-started/). I had the same issue when I was setting up mkdocs in GH Actions. The solution is to pin some of the mkdocs dependencies to older versions (as used by Travis). [Details are in this commit](https://github.com/JMadgwick/oi-docs/commit/e5f515f42a2e9c8bf4d67c8996d3200fd6c58738).

Can you make a PR for that commit? Then we can fix that aswell in Production now.

**Pull request merged**
