### PR TITLE
Create zone configuration section

### PR DESCRIPTION
**Pull request by pyhalov**

### CODE REVIEW

**Comment by pyhalov** [comment]
What does Travis want from me?

**Comment by xen0l** [comment]
@pyhalov fix mdl warning, the mkdocs error is something I am looking into. @makruger any ideas?

**Comment by makruger** [comment]
markdown lint is rather particular about trailing spaces and wanting code blocks surrounded by spaces.

mdl -s markdownlint-rules.rb .
./docs/handbook/systems-administration.md:421: MD009 Trailing spaces
./docs/handbook/systems-administration.md:429: MD009 Trailing spaces
./docs/handbook/systems-administration.md:430: MD009 Trailing spaces
./docs/handbook/systems-administration.md:431: MD009 Trailing spaces
./docs/handbook/systems-administration.md:457: MD009 Trailing spaces
./docs/handbook/systems-administration.md:462: MD009 Trailing spaces
./docs/handbook/systems-administration.md:410: MD031 Fenced code blocks should be surrounded by blank lines
./docs/handbook/systems-administration.md:436: MD031 Fenced code blocks should be surrounded by blank lines
./docs/handbook/systems-administration.md:438: MD031 Fenced code blocks should be surrounded by blank lines
./docs/handbook/systems-administration.md:442: MD031 Fenced code blocks should be surrounded by blank lines
./docs/handbook/systems-administration.md:472: MD031 Fenced code blocks should be surrounded by blank lines
./docs/handbook/systems-administration.md:479: MD031 Fenced code blocks should be surrounded by blank lines
./docs/handbook/systems-administration.md:485: MD031 Fenced code blocks should be surrounded by blank lines
./docs/handbook/systems-administration.md:495: MD031 Fenced code blocks should be surrounded by blank lines

**Comment by makruger** [comment]
OK, this build error is reproducible. I did a `pip install --upgrade mkdocs` and then everything exploded. It looks to be a problem with our theme when used with the latest version of mkdocs, as changing the theme within mkdocs.yml to "readthedocs" resolves the build issue. However, the site then looks terrible. I'll try a few other themes, maybe we can find something visually acceptable which works. Our theme is spacelab which is part of mkdocs-bootswatch (which apparently needs updating).

**Comment by pyhalov** [comment]
People, perhaps we should just package necessary tools to avoid unexpected version bumps?

**Comment by makruger** [comment]
https://github.com/mkdocs/mkdocs-bootswatch/issues/35

**Comment by pyhalov** [comment]
There's already too many commits in this PR, when somebody merges it, please, squash commits.

**Comment by makruger** [comment]
Possible alternative theme: https://squidfunk.github.io/mkdocs-material/

 Actively developed and has lots of options. We would however, need to modify some things to work with the new theme. A bit tedious, but doable.

**Comment by pyhalov** [comment]
I've just forced Travis to use mkdocs 0.15.2 for now

**Pull request merged**
