### PR TITLE
Add OI 2019.10 release notes

### PR DESCRIPTION
**Pull request by pyhalov**

### CODE REVIEW

**Comment by pyhalov** [comment]
@AndWac

**Comment by pyhalov** [comment]
Feel free to edit further...

**Comment by citrus-it** [comment]
Some things to consider:

* Did you pick up the new `netstat -u` before this snapshot?
* UEFI boot improvements/support? `bootadm update-archive` now populates/maintains the ESP.
* 11553 Want pluggable TCP congestion control algorithms
* The default crypt algorithm is now SHA512
* crontab support for step, i.e. `*/2`

**Comment by Mno-hime** [comment]
Thanks @citrus-it, I added all of your suggestions, appreciate your involvement.

**Pull request merged**
