### PR TITLE
Add notes on building Ruby 3.0.2 and installing Vagrant

### PR DESCRIPTION
**Pull request by cstes**
Notes on installing Vagrant.

Also modify the notes on Oracle Database because there are Vagrantfiles from Oracle to install recent Oracle Databases (RAC, Grid, Oracle 18, 19, 21.3 etc.)

### CODE REVIEW

**Comment by pyhalov** [comment]
Why are we recommending to avoid using system Ruby? 
Why we just don't pack vagrant?

Strong -1 for including such advices in official documentation.

**Comment by cstes** [comment]
First of all my notes are clearly marked as community provided and not as official OpenIndiana documentation. The notes are in the community directory.   If OpenIndiana is a community project then this pull request could add some useful notes that everybody will understand are NOT written by the OpenIndiana team but are just community provided by myself as an OpenIndiana user.  I understand that an IPS vagrant package would be useful for operating system updates.  Ideally that package would be maintained and made by Hashicorp.  Hashicorp hosts a repository for Debian APT/RPM YUM and other package systems.  In addition Hashicorp has a pricing policy (see hashicorp.com/pricing) to sell their products such as Vagrant and HCP cloud and other cloud products.   But I am afraid that OpenIndiana users currently will simply use a different OS, one of the operating systems that Hashicorp supports, instead of using OI.   And Hashicorp will think there are not many OI users and not do any effort thus to make an IPS package. I've asked Hashicorp 2 months ago for an IPS package and they don't respond.  Somebody pointed out that Vagrant may change from Ruby to GoLang and then the work on a package must be redone ... The policy of Hashicorp is (according to their build instructions) that unsupported operating systems such as OpenIndiana should build from source and should avoid using the system provided Ruby.    

I've tested with Ruby 3.0.2 and Ruby 3.1.0dev

/scratch/ruby-31/bin/ruby --version           
ruby 3.1.0dev (2021-09-15T13:59:37Z master db51bcada4) [i386-solaris2.11]

The possibility to run Vagrant on OpenIndiana could be very useful to attract users to OpenIndiana.

Creating an IPS package for Vagrant is a lot of work and may be counter productive at this moment because it is against the stated policies of Hashicorp.  Hashicorp is best placed to support the product.  It is their product.

Also there is other work to be done such as updating the openindiana box in the vagrant cloud and creating a different openindiana box with MATE desktop installed for example, or boxes specifically for building oi-userland.

So I hope my notes can be added and may help others as a starting point.

**Comment by pyhalov** [comment]
First of all, why should we care about invalid recommendations?
Not using system ruby automatically means running something unmaintained. 
At least we could provide new ruby version if not vagrant itself.

I can understand recommendations on compiling unusual software, but vagrant seems to be something one expects to find in distribution. And it's not hard to package it if someone is interested - https://github.com/omniosorg/omnios-extra/tree/master/build/vagrant

**Comment by cstes** [comment]
This "how to build Vagrant" document in a simple blog-like style is a just a PR request to add community provided notes in the clearly community contributed section of the docs.  For those who wonder whether Vagrant can be built at all on OpenIndiana it may be useful.

**Comment by pyhalov** [comment]
I understand that these notes have value. But what I also feel that it looks weird. We document how to alleviate the pain OI puts on you when one tries to build vagrant instead of solving the issue itself - just provide vagrant. I'd say it would look fine if vagrant was closed source, hard to port or it was a wiki article. But documenting it on the site seems ugly...

**Comment by cstes** [comment]
It is just pragmatic not ugly.   Some users may be able to follow the instructions and have it set up and working without problems.   For those users who complain that they want an easier to use IPS package,two things can be done:  1) support those users by OI itself (for which we do not have the resources) or 2) tell them to go ask for support to Hashicorp.    If Hashicorp support finds out about the request or problem they will ask the users anyway not to use the system provided packages.

**Comment by pyhalov** [comment]
The first thing they'll say: use supported operating system. Point. 
Don't hope someone is going to support OI/illumos if you don't come up with patches.
If you come with patches, third parties can accept them. Or not, stating that Solaris is dead for 10 years and they haven't heard about OI.

**Comment by AndWac** [comment]
I wholeheartedly concur Alexander's sentiments regarding creating packages.

**Comment by cstes** [comment]
Although it is true that an IPS package has many advantages for OS upgrades, in this particular case I think an IPS package is not a good idea because if the maintainer is not hashicorp, then hashicorp will perceive the IPS package as something that is unrelated to them, while they (Hashicorp) are the actual developers/maintainers.   Anyway I am not waiting nor asking for an IPS vagrant package just to run the vagrant scripts which seem to work fine on OpenIndiana.   That's all the notes were meant to state anyway.   These notes are not meant to criticise IPS packages in general, I like IPS packages, but in this case you can perfectly well use the vagrant scripts and build them directly from the Hashicorp git repo.   I sympathise with Hashicorp for providing the git repo as some sort of support for operating systems like OpenIndiana.

**Comment by pyhalov** [comment]
I don't understand your argument. If I follow it, we should avoid shipping PostgreSQL, as we are not a PGDG?

**Comment by cstes** [comment]
As far as I know the recommendations of PostgreSQL are not to avoid the system provided Ruby.     I can understand that you disagree with the statement of Hashicorp, but that's their statement.   I think the "build from source" instructions for PostgreSQL may be different (better?) maybe they encourage users to use the system provided tools.  But in this particular case, it seems , Hashicorp does not have a high/good opinion about system provided Ruby versions.   Given the fact that OpenIndiana has a good recent ruby-26 that is unfair from Hashicorp but it's just their opinion ...

**Comment by pyhalov** [comment]
Just update it and be done with it ;)

**Comment by cstes** [comment]
Vagrant also works with Ruby 3.1.0dev .

The Ruby team seems to have fixed the "bison issue"

See bison issue possibly the one I experience on OpenIndiana in 3.0.2 : 

https://bugs.ruby-lang.org/issues/18166

The workaround in ruby 3.0.2 that I document in the notes for this commit is:

 touch ruby-3.0.2/ext/ripper/ripper.c

However that workaround is not required any longer in the new (not yet released) Ruby 3.1.

Anyway waiting for Ruby 3.1 is not really required.

These notes only document the simple "./configure - gmake - gmake install" approach that works and produces a locally-built vagrant printing out the following message:

```
$ vagrant box list
You appear to be running Vagrant outside of the official installers.
Note that the installers are what ensure that Vagrant has all required
dependencies, and Vagrant assumes that these dependencies exist. By
running outside of the installer environment, Vagrant may not function
properly. To remove this warning, install Vagrant using one of the
official packages from vagrantup.com.

openindiana/hipster (virtualbox, 20210302)
```

Meanwhile the OpenIndiana image (box) in the vagrant cloud was updated:

```
$ vagrant box list                                 
You appear to be running Vagrant outside of the official installers.
Note that the installers are what ensure that Vagrant has all required
dependencies, and Vagrant assumes that these dependencies exist. By
running outside of the installer environment, Vagrant may not function
properly. To remove this warning, install Vagrant using one of the
official packages from vagrantup.com.

openindiana/hipster (virtualbox, 202109)
```

The fact that vagrant works is an asset for OpenIndiana.   The community provided notes only reflect my usage of OpenIndiana as "community member".

I also suspect that doing work at this point in a Vagrant package may be counterproductive.

Supporting the Vagrant cloud on the other hand (for example by adding more boxes) would be work that would be more in line with my Smalltalk-80 contribution.

I am thinking of trying to upload Cuis/Smalltalk vagrant boxes built on top of the OpenIndiana box.

**Comment by cstes** [comment]
The message that Vagrant prints:

`You appear to be running Vagrant outside of the official installers.
Note that the installers are what ensure that Vagrant has all required
dependencies, and Vagrant assumes that these dependencies exist. By
running outside of the installer environment, Vagrant may not function
properly. To remove this warning, install Vagrant using one of the
official packages from vagrantup.com.
`

is also what convinces me most that an IPS package of vagrant is not such a good idea.

The reaction of Hashicorp may be to explicitely to NOT support OpenIndiana when they see that OI packages vagrant.

The initiative to support OpenIndiana (and to get rid of the silly message above) must come from Hashicorp.

As long as that is not the case, we can simply use the compile from source solution.

**Comment by JMadgwick** [comment]
I have no particular comment on the nature of the PR, though I concur that not having the endorsement of Hashicorp alone doesn't seem to be a good reason for not packaging.
I noticed there was a problem with the automated build. This was caused by the GitHub Actions runner image having an outdated apt cache and our Action omitting a step to update it. It seems this had the potential to cause sporadic build failures. I've now fixed the Actions config and rerun the checks on this PR. **It's now good to merge.**

**Comment by cstes** [comment]
Thanks for technically making sure that all checks have passed now for merging this commit.

The PR for the oi-userland/Vagrantfile  (supporting "vagrant up" in the oi-userland directory) was merged yesterday.

One of the many arguments that I still have for simply using the procedure that Hashicorp proposes themselves at [Installing Vagrant from Source](https://www.vagrantup.com/docs/installation/source) is that there exist many competing products.

There is Hashicorp with the their cloud, but many other cloud products, it is in some sense an endorsement of Hashicorp to package the Vagrant package, which may be counterproductive not only against the wish of Hashicorp but also upsetting other cloud vendors / companies active with competing products.

So this PR for documentation update seems a neutral approach where OpenIndiana docs only refer to the Hashicorp documentation.

OpenIndiana can (and probably should) update their base packages like golang, ruby, bison, gcc, clang compiler technology etc. for making the build from source possible.

**Comment by cstes** [comment]
Add comment in the handbook.  In the vagrant section it stated:

_Vagrant is officially available for Mac OS X, Windows and Linux._

This is correct but I added a comment that it can also be compiled and works on OpenIndiana.   Additionally the handbook says "only text console is available";  but by using the vagrant box, I have found the interesting possibility of running GUI apps over SSH X11 forwarding with vagrant, so the box also supports GUI apps over SSH.

**Comment by cstes** [comment]
As a user contribution I think this information could be useful.    Personally I don't mind using unpackaged software, it is actuallly a feature (strenght) of IPS that it can coexist with different installation methods such as compiling from source (or other installers).   So hopefull this can be added , even if temporary ....   Who knows, maybe if there is sufficient interest there could be an initiative at Hashicorp to make a package for OpenIndiana ...

**Comment by JMadgwick** [comment]
Seems like a useful contribution to me. Are you ready for this to be merged?

**Comment by cstes** [comment]
Because OpenIndiana is a community driven project, this contirbution can be interpreted as a positive thing, namely htat it is  reported by some people in the community that it is possible to build certain packages from source.   The contribution is clearly marked as community contributed , and is not really part of the main OpenIndiana official documentation.

**Pull request merged**
